### ISSUE TITLE
666

### ISSUE THREAD

**Issue by WillzenZou** [killLuoti/python_yiban#1]
点赞动态："https://mobile.yiban.cn/api/v3/feeds/" + feedId + "/ups", data={"access_token": access_token}
同情动态："https://mobile.yiban.cn/api/v3/feeds/" + feedId + "/downs", data={"access_token": access_token}
评论动态："https://mobile.yiban.cn/api/v3/feeds/" + feedId + "/comments",data={"access_token": access_token, "content": yiyan, "toUserId": "", "toCommentId": ""}
点赞易喵喵：'https://ymm.yiban.cn/news/like/click?recommend_type=0', data={"id" : i}
评论易喵喵：'https://ymm.yiban.cn/news/comment/add?recommend_type=0', data={  'id': i, 'comment': yiyan  }

最好整个项目关了重新上传，github能看到以前提交记录
顺带一提，我是隔壁顺职的

**Comment by killLuoti** [comment]
谢谢提醒
